// AUTO-GENERATED by the catalog backfill/importer. DO NOT EDIT BY HAND.
// Byte-equal to CatalogRelease v1's snapshot. Web build-time fallback for
// getPublishedCatalog when the catalog DB is empty/unreachable — the site never 500s.
import type { CatalogSnapshot } from "@signex/shared";

export const INITIAL_CATALOG: CatalogSnapshot = {
  "categories": [
    {
      "id": "cmqwcchk1v87zcbmexgi",
      "tag": {
        "en": "PVC · Silicone",
        "vi": "PVC · Silicone"
      },
      "slug": "plastic-logos-emblems",
      "image": {
        "mime": "image/avif",
        "r2Key": "originals/cd18e3b1444659de0a5b6b7479112caf/69b049a16076b1b2188d012d-rumman-amin-s3o2rktkf7i-unsplash.avif",
        "width": 2400,
        "height": 3600,
        "assetId": "ccd18e3b1444659de0a5b6b74",
        "variants": []
      },
      "intro": {
        "en": "Molded and printed plastic brand marks engineered to hold crisp logo geometry and stable color through repeated wash and wear. From soft-PVC patches to silicone heat-transfers and 3D domed emblems, each piece is tooled to your brand spec and finished for apparel, footwear, bags, and accessories.",
        "vi": "Logo và biểu tượng nhựa được đúc và in nhằm giữ nét logo sắc sảo cùng màu sắc ổn định qua nhiều lần giặt và sử dụng. Từ nhãn PVC mềm, logo ép nhiệt silicone đến biểu tượng nổi 3D, mỗi chi tiết đều được làm khuôn theo thông số thương hiệu và hoàn thiện cho hàng may mặc, giày dép, túi xách và phụ kiện."
      },
      "items": [
        {
          "id": "cmqwcchk16daqumz7c8l",
          "tag": {
            "en": "Soft PVC",
            "vi": "PVC mềm"
          },
          "desc": {
            "en": "Flexible 2D or 3D soft-PVC patch with sharp molded detail and a sew-on or heat-seal backing for garments and caps.",
            "vi": "Nhãn PVC mềm 2D hoặc 3D với chi tiết đúc sắc nét, mặt sau may hoặc ép nhiệt, dùng cho quần áo và mũ nón."
          },
          "slug": "soft-pvc-logo-patch",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/de4dedb21ef3f3df9b6636351a554c56/69a9a5725487307243a72031-pexels-adriendrj-33980501.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "cde4dedb21ef3f3df9b663635",
            "variants": []
          },
          "title": {
            "en": "Soft-PVC logo patch",
            "vi": "Nhãn logo PVC mềm"
          },
          "sortOrder": 0
        },
        {
          "id": "cmqwcchk1uazbjorq79r",
          "tag": {
            "en": "Silicone",
            "vi": "Silicone"
          },
          "desc": {
            "en": "Thin, stretchable silicone mark heat-pressed directly onto fabric for a clean, tagless branded finish.",
            "vi": "Logo silicone mỏng, co giãn, ép nhiệt trực tiếp lên vải, cho bề mặt thương hiệu sạch và không cần nhãn may."
          },
          "slug": "silicone-heat-transfer-logo",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/b3c0bc5aa6391c8b09cbf9c8fb3836ae/69a9a51013e52d8aa1532730-pexels-alohaphotostudio-6961666.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "cb3c0bc5aa6391c8b09cbf9c8",
            "variants": []
          },
          "title": {
            "en": "Silicone heat-transfer logo",
            "vi": "Logo ép nhiệt silicone"
          },
          "sortOrder": 1
        },
        {
          "id": "cmqwcchk1c0tb6zig0t",
          "tag": {
            "en": "Domed Resin",
            "vi": "Phủ keo nổi"
          },
          "desc": {
            "en": "Printed insert sealed under a glossy doming resin for a raised, scratch-resistant emblem on bags and accessories.",
            "vi": "Tem in được phủ lớp keo PU bóng nổi, tạo biểu tượng cộm chống trầy cho túi xách và phụ kiện."
          },
          "slug": "3d-domed-resin-emblem",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/558390147010589195a164982f35768c/69a9a43eeca7b6045e93b8cd-pexels-freestockpro-1007657.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "c558390147010589195a16498",
            "variants": []
          },
          "title": {
            "en": "3D domed resin emblem",
            "vi": "Biểu tượng nổi phủ keo PU"
          },
          "sortOrder": 2
        },
        {
          "id": "cmqwcchk1ry08d0kazyb",
          "tag": {
            "en": "PU Rubber",
            "vi": "Cao su PU"
          },
          "desc": {
            "en": "Multi-layer rubberized PU badge with embossed edges, giving a soft-touch feel and strong color contrast.",
            "vi": "Logo cao su PU nhiều lớp với viền dập nổi, cho cảm giác mềm tay và độ tương phản màu cao."
          },
          "slug": "rubberized-pu-badge",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/85ab32c93251f71a2e485ad38e029b6a/69a9a3f79f4956225122393e-pexels-shameel-mukkath-3421394-15059057-1.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "c85ab32c93251f71a2e485ad3",
            "variants": []
          },
          "title": {
            "en": "Rubberized PU badge",
            "vi": "Logo cao su PU"
          },
          "sortOrder": 3
        },
        {
          "id": "cmqwcchk1uq07jctwqd",
          "tag": {
            "en": "Molded TPU",
            "vi": "TPU ép phun"
          },
          "desc": {
            "en": "Hard injection-molded TPU logo with precise edges and fixing posts for footwear and structured bags.",
            "vi": "Logo TPU ép phun cứng với cạnh sắc nét và chấu gắn, dùng cho giày dép và túi có cấu trúc."
          },
          "slug": "injection-molded-logo-trim",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/a0c5792c16ff36fde7aad11d2f05a4e4/69a9a296fd1002040c1e9240-pexels-brett-sayles-2126124.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "ca0c5792c16ff36fde7aad11d",
            "variants": []
          },
          "title": {
            "en": "Injection-molded logo trim",
            "vi": "Logo nhựa ép phun"
          },
          "sortOrder": 4
        },
        {
          "id": "cmqwcchk12oo346q8aop",
          "tag": {
            "en": "Embossed PVC",
            "vi": "PVC dập nổi"
          },
          "desc": {
            "en": "Tonal embossed PVC label with raised lettering and stitch channels for a subtle, durable brand mark.",
            "vi": "Nhãn PVC dập nổi cùng tông, chữ nổi và rãnh may sẵn, tạo dấu hiệu thương hiệu tinh tế và bền."
          },
          "slug": "embossed-pvc-label",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/43f0ecc88ceaad99e422630f471df5fd/69a9a01bdb6ad07ce787019a-pexels-slimmars-13-197677686-13801311.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "c43f0ecc88ceaad99e422630f",
            "variants": []
          },
          "title": {
            "en": "Embossed PVC label",
            "vi": "Nhãn PVC dập nổi"
          },
          "sortOrder": 5
        }
      ],
      "title": {
        "en": "Plastic logos & emblems",
        "vi": "Logo & biểu tượng nhựa"
      },
      "sortOrder": 0,
      "productCount": 18,
      "materialCount": 4
    },
    {
      "id": "cmqwcchk12jomdzhjvbp",
      "tag": {
        "en": "Woven · Printed",
        "vi": "Dệt · In"
      },
      "slug": "labels-badges-nameplates",
      "image": {
        "mime": "image/avif",
        "r2Key": "originals/47aeed00890ae34ee187193dc6a8f823/69b037b7b9f0bc0f27d8889d-dinuka-lankaloka-hkr5cn6s0q0-unsplash.avif",
        "width": 2400,
        "height": 1600,
        "assetId": "c47aeed00890ae34ee187193d",
        "variants": []
      },
      "intro": {
        "en": "Woven, printed and heat-pressed identity trims that carry your brand mark, care information and sizing directly on the garment — produced to consistent specification, batch after batch.",
        "vi": "Các loại nhãn dệt, nhãn in và nhãn ép mang logo, thông tin bảo quản và size ngay trên sản phẩm — gia công đúng quy cách, đồng nhất qua từng lô hàng."
      },
      "items": [
        {
          "id": "cmqwcchk1qfbqq5kvee8",
          "tag": {
            "en": "Woven Damask",
            "vi": "Dệt damask"
          },
          "desc": {
            "en": "High-density damask weave with crisp logo definition and a soft hand-feel for main and neck labels.",
            "vi": "Nhãn dệt damask mật độ cao cho logo sắc nét, mềm tay, dùng làm nhãn chính và nhãn gáy cổ áo."
          },
          "slug": "woven-damask-brand-label",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/de4dedb21ef3f3df9b6636351a554c56/69a9a5725487307243a72031-pexels-adriendrj-33980501.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "cde4dedb21ef3f3df9b663635",
            "variants": []
          },
          "title": {
            "en": "Woven Damask Brand Label",
            "vi": "Nhãn dệt damask"
          },
          "sortOrder": 0
        },
        {
          "id": "cmqwcchk1jpaef0wdmo",
          "tag": {
            "en": "Printed Satin",
            "vi": "In satin"
          },
          "desc": {
            "en": "Smooth satin ribbon printed with wash-care symbols, fiber content and country of origin.",
            "vi": "Dải satin mịn in ký hiệu giặt là, thành phần sợi và xuất xứ, dùng làm nhãn bảo quản."
          },
          "slug": "printed-satin-care-label",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/b3c0bc5aa6391c8b09cbf9c8fb3836ae/69a9a51013e52d8aa1532730-pexels-alohaphotostudio-6961666.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "cb3c0bc5aa6391c8b09cbf9c8",
            "variants": []
          },
          "title": {
            "en": "Printed Satin Care Label",
            "vi": "Nhãn in satin"
          },
          "sortOrder": 1
        },
        {
          "id": "cmqwcchk1ztk5jkcxeoi",
          "tag": {
            "en": "Cotton / Polyester",
            "vi": "Cotton / Polyester"
          },
          "desc": {
            "en": "Center-fold or end-fold size and care tabs with clean cut edges, sewn into seams or side panels.",
            "vi": "Nhãn size, nhãn bảo quản gấp giữa hoặc gấp một biên, bo mép gọn, may vào đường ráp hoặc sườn áo."
          },
          "slug": "folded-size-care-tab",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/558390147010589195a164982f35768c/69a9a43eeca7b6045e93b8cd-pexels-freestockpro-1007657.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "c558390147010589195a16498",
            "variants": []
          },
          "title": {
            "en": "Folded Size & Care Tab",
            "vi": "Nhãn size gấp biên"
          },
          "sortOrder": 2
        },
        {
          "id": "cmqwcchk162gqt1dtn7x",
          "tag": {
            "en": "Heat-Transfer",
            "vi": "Ép nhiệt"
          },
          "desc": {
            "en": "Tagless heat-transfer labels pressed directly onto the fabric for soft, irritation-free care marking.",
            "vi": "Nhãn ép nhiệt không cấn cổ, ép trực tiếp lên vải cho cảm giác mềm mại, êm da."
          },
          "slug": "heat-transfer-label",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/85ab32c93251f71a2e485ad38e029b6a/69a9a3f79f4956225122393e-pexels-shameel-mukkath-3421394-15059057-1.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "c85ab32c93251f71a2e485ad3",
            "variants": []
          },
          "title": {
            "en": "Heat-Transfer Label",
            "vi": "Nhãn ép nhiệt"
          },
          "sortOrder": 3
        },
        {
          "id": "cmqwcchk11dhap64mul6",
          "tag": {
            "en": "Zinc / Brass",
            "vi": "Kẽm / Đồng"
          },
          "desc": {
            "en": "Engraved or etched zinc and brass nameplates with electroplated finish for bags and outerwear.",
            "vi": "Bảng tên kim loại kẽm hoặc đồng, khắc hoặc ăn mòn, mạ điện hoàn thiện, gắn trên túi xách và áo khoác."
          },
          "slug": "engraved-metal-nameplate",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/a0c5792c16ff36fde7aad11d2f05a4e4/69a9a296fd1002040c1e9240-pexels-brett-sayles-2126124.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "ca0c5792c16ff36fde7aad11d",
            "variants": []
          },
          "title": {
            "en": "Engraved Metal Nameplate",
            "vi": "Bảng tên kim loại"
          },
          "sortOrder": 4
        },
        {
          "id": "cmqwcchk1w9pyod4udg",
          "tag": {
            "en": "Embroidered",
            "vi": "Thêu vi tính"
          },
          "desc": {
            "en": "Dense machine-embroidered badges with merrowed or laser-cut borders and iron-on or sew-on backing.",
            "vi": "Phù hiệu thêu vi tính dày, viền vắt sổ hoặc cắt laser, đế ép keo hoặc may đính."
          },
          "slug": "embroidered-badge",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/43f0ecc88ceaad99e422630f471df5fd/69a9a01bdb6ad07ce787019a-pexels-slimmars-13-197677686-13801311.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "c43f0ecc88ceaad99e422630f",
            "variants": []
          },
          "title": {
            "en": "Embroidered Badge",
            "vi": "Phù hiệu thêu"
          },
          "sortOrder": 5
        }
      ],
      "title": {
        "en": "Labels, badges, nameplates",
        "vi": "Nhãn, phù hiệu & bảng tên"
      },
      "sortOrder": 1,
      "productCount": 24,
      "materialCount": 6
    },
    {
      "id": "cmqwcchk1wnn1vc0wt3l",
      "tag": {
        "en": "Bespoke",
        "vi": "Đặt riêng"
      },
      "slug": "custom-identity-components",
      "image": {
        "mime": "image/avif",
        "r2Key": "originals/68e3e1726da687d5f9c720ee927c27f1/69b03783cb355b95794c522e-pexels-roman-odintsov-5667901.avif",
        "width": 2500,
        "height": 1405,
        "assetId": "c68e3e1726da687d5f9c720ee",
        "variants": []
      },
      "intro": {
        "en": "Bespoke metal and molded trims engineered to your brand specification, from zipper pulls to rivets and snaps. Each component is tooled to order in zinc alloy, brass, TPU, or soft PVC with custom finishes, logos, and engraving for a consistent identity across every garment.",
        "vi": "Phụ liệu kim loại và đúc khuôn đặt riêng theo đúng yêu cầu thương hiệu, từ tay kéo khóa đến đinh tán và nút bấm. Mỗi chi tiết được làm khuôn theo đơn bằng hợp kim kẽm, đồng thau, TPU hoặc PVC mềm với lớp hoàn thiện, logo và khắc tùy chỉnh, giữ nhận diện đồng nhất trên từng sản phẩm."
      },
      "items": [
        {
          "id": "cmqwcchk1gdunhx3ngc7",
          "tag": {
            "en": "Zinc Alloy",
            "vi": "Hợp kim kẽm"
          },
          "desc": {
            "en": "Die-cast zinc-alloy pulls shaped to your logo with electroplated or matte finishes for jackets, bags, and outerwear.",
            "vi": "Tay kéo đúc hợp kim kẽm tạo hình theo logo, mạ điện hoặc hoàn thiện mờ, dùng cho áo khoác, túi và đồ mặc ngoài."
          },
          "slug": "branded-zipper-pulls",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/de4dedb21ef3f3df9b6636351a554c56/69a9a5725487307243a72031-pexels-adriendrj-33980501.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "cde4dedb21ef3f3df9b663635",
            "variants": []
          },
          "title": {
            "en": "Branded zipper pulls",
            "vi": "Tay kéo khóa khắc logo"
          },
          "sortOrder": 0
        },
        {
          "id": "cmqwcchk1iyvc6wl5z3",
          "tag": {
            "en": "Brass",
            "vi": "Đồng thau"
          },
          "desc": {
            "en": "Solid brass shank and tack buttons with laser-engraved or embossed brand marks in antique, nickel, or gunmetal plating.",
            "vi": "Nút cài và nút tán bằng đồng thau khắc laser hoặc dập nổi nhãn hiệu, mạ giả cổ, niken hoặc xám súng."
          },
          "slug": "engraved-metal-buttons",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/b3c0bc5aa6391c8b09cbf9c8fb3836ae/69a9a51013e52d8aa1532730-pexels-alohaphotostudio-6961666.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "cb3c0bc5aa6391c8b09cbf9c8",
            "variants": []
          },
          "title": {
            "en": "Engraved metal buttons",
            "vi": "Nút kim loại khắc nhãn"
          },
          "sortOrder": 1
        },
        {
          "id": "cmqwcchk16wqrjq5aoae",
          "tag": {
            "en": "Zinc · Acetal",
            "vi": "Kẽm · Acetal"
          },
          "desc": {
            "en": "Made-to-spec side-release and slide buckles cast in zinc or molded in acetal, debossed with your mark for straps and webbing.",
            "vi": "Khóa nhả nhanh và khóa trượt làm theo quy cách, đúc kẽm hoặc ép acetal, dập chìm nhãn hiệu cho dây đai và dây dệt."
          },
          "slug": "custom-logo-buckles",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/558390147010589195a164982f35768c/69a9a43eeca7b6045e93b8cd-pexels-freestockpro-1007657.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "c558390147010589195a16498",
            "variants": []
          },
          "title": {
            "en": "Custom logo buckles",
            "vi": "Khóa cài dập logo"
          },
          "sortOrder": 2
        },
        {
          "id": "cmqwcchk1u3yvqt1xl8j",
          "tag": {
            "en": "Brass Cap",
            "vi": "Đầu đồng thau"
          },
          "desc": {
            "en": "Double-cap rivets and decorative studs with a stamped logo head, finished in brass, copper, or black nickel for denim and leather goods.",
            "vi": "Đinh tán hai đầu và đinh trang trí dập logo trên đầu, hoàn thiện đồng thau, đồng đỏ hoặc niken đen cho hàng jeans và đồ da."
          },
          "slug": "logo-rivets-studs",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/85ab32c93251f71a2e485ad38e029b6a/69a9a3f79f4956225122393e-pexels-shameel-mukkath-3421394-15059057-1.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "c85ab32c93251f71a2e485ad3",
            "variants": []
          },
          "title": {
            "en": "Logo rivets & studs",
            "vi": "Đinh tán khắc logo"
          },
          "sortOrder": 3
        },
        {
          "id": "cmqwcchk1o7d9rgu4v5",
          "tag": {
            "en": "Soft PVC",
            "vi": "PVC mềm"
          },
          "desc": {
            "en": "Injection-molded spring cord stoppers and aglets in soft PVC or TPU, raised with a 3D logo and matched to brand Pantone colors.",
            "vi": "Chốt chặn dây lò xo và đầu bọc dây ép phun bằng PVC mềm hoặc TPU, logo nổi 3D và pha màu khớp Pantone thương hiệu."
          },
          "slug": "branded-cord-stoppers",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/a0c5792c16ff36fde7aad11d2f05a4e4/69a9a296fd1002040c1e9240-pexels-brett-sayles-2126124.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "ca0c5792c16ff36fde7aad11d",
            "variants": []
          },
          "title": {
            "en": "Branded cord stoppers",
            "vi": "Chốt chặn dây logo nổi"
          },
          "sortOrder": 4
        },
        {
          "id": "cmqwcchk1yonob3fz48",
          "tag": {
            "en": "Plated Metal",
            "vi": "Kim loại mạ"
          },
          "desc": {
            "en": "Self-piercing eyelets, grommets, and ring-spring snap fasteners engraved with your logo in nickel, brass, or matte-black plating.",
            "vi": "Khoen xỏ tự đột, ô-dê và nút bấm bốn phần khắc logo, mạ niken, đồng thau hoặc đen mờ."
          },
          "slug": "logo-eyelets-snaps",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/43f0ecc88ceaad99e422630f471df5fd/69a9a01bdb6ad07ce787019a-pexels-slimmars-13-197677686-13801311.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "c43f0ecc88ceaad99e422630f",
            "variants": []
          },
          "title": {
            "en": "Logo eyelets & snaps",
            "vi": "Ô-dê & nút bấm khắc nhãn"
          },
          "sortOrder": 5
        }
      ],
      "title": {
        "en": "Custom identity components",
        "vi": "Linh kiện nhận diện tùy chỉnh"
      },
      "sortOrder": 2,
      "productCount": 15,
      "materialCount": 5
    },
    {
      "id": "cmqwcchk16ihcfucem1p",
      "tag": {
        "en": "OEM Spec",
        "vi": "Chuẩn OEM"
      },
      "slug": "oem-brand-parts",
      "image": {
        "mime": "image/avif",
        "r2Key": "originals/6729c31c0192e90813086218ca51bdce/69aff4da51c27aa9c99aba98-pexels-keeganjchecks-14524361.avif",
        "width": 2500,
        "height": 1405,
        "assetId": "c6729c31c0192e90813086218",
        "variants": []
      },
      "intro": {
        "en": "OEM brand parts produced to your exact spec sheet — co-developed trim sets, private-label labels, and branded hardware kits matched to your brand standards. We build to drawing, color, and tolerance, then deliver consistently at production scale.",
        "vi": "Linh kiện thương hiệu OEM sản xuất theo đúng spec sheet của bạn — bộ phụ liệu phát triển chung, nhãn private-label và bộ phụ kiện gắn logo theo chuẩn nhận diện thương hiệu. Chúng tôi làm theo bản vẽ, màu sắc và dung sai, đảm bảo đồng nhất ở quy mô sản xuất hàng loạt."
      },
      "items": [
        {
          "id": "cmqwcchk11fdk9hkfgkd",
          "tag": {
            "en": "Mixed materials",
            "vi": "Đa vật liệu"
          },
          "desc": {
            "en": "A coordinated set of labels, tags, and hardware co-developed and color-matched to your brand spec sheet for a single garment program.",
            "vi": "Bộ phụ liệu đồng bộ gồm nhãn, tag treo và phụ kiện kim loại được phát triển chung và đồng màu theo spec sheet thương hiệu cho từng chương trình hàng."
          },
          "slug": "spec-matched-trim-set",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/de4dedb21ef3f3df9b6636351a554c56/69a9a5725487307243a72031-pexels-adriendrj-33980501.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "cde4dedb21ef3f3df9b663635",
            "variants": []
          },
          "title": {
            "en": "Spec-matched trim set",
            "vi": "Bộ phụ liệu theo spec"
          },
          "sortOrder": 0
        },
        {
          "id": "cmqwcchk14g0tr8yqekh",
          "tag": {
            "en": "Woven damask",
            "vi": "Dệt damask"
          },
          "desc": {
            "en": "A damask-woven main label produced under your own private label, with brand-locked colors, fonts, and folding to your tech pack.",
            "vi": "Nhãn chính dệt damask sản xuất dưới thương hiệu riêng của bạn, khóa màu, font và kiểu gấp theo đúng tech pack."
          },
          "slug": "private-label-woven-label",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/b3c0bc5aa6391c8b09cbf9c8fb3836ae/69a9a51013e52d8aa1532730-pexels-alohaphotostudio-6961666.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "cb3c0bc5aa6391c8b09cbf9c8",
            "variants": []
          },
          "title": {
            "en": "Private-label woven label",
            "vi": "Nhãn dệt private-label"
          },
          "sortOrder": 1
        },
        {
          "id": "cmqwcchk1guu03ou65ce",
          "tag": {
            "en": "Zinc alloy",
            "vi": "Hợp kim kẽm"
          },
          "desc": {
            "en": "A packaged kit of branded zipper pullers, rivets, and snaps die-cast and electroplated to your logo and finish standard.",
            "vi": "Bộ phụ kiện đóng gói gồm đầu khóa kéo, đinh tán và nút bấm gắn logo, đúc và mạ điện theo chuẩn logo và bề mặt của bạn."
          },
          "slug": "branded-hardware-kit",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/558390147010589195a164982f35768c/69a9a43eeca7b6045e93b8cd-pexels-freestockpro-1007657.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "c558390147010589195a16498",
            "variants": []
          },
          "title": {
            "en": "Branded hardware kit",
            "vi": "Bộ phụ kiện gắn logo"
          },
          "sortOrder": 2
        },
        {
          "id": "cmqwcchk148xety5rh29",
          "tag": {
            "en": "Genuine leather",
            "vi": "Da thật"
          },
          "desc": {
            "en": "A debossed leather patch developed jointly with your design team, with hide grade, edge finish, and stitch spec fixed to drawing.",
            "vi": "Nhãn da dập chìm phát triển cùng đội thiết kế của bạn, cố định loại da, xử lý cạnh và quy cách đường may theo bản vẽ."
          },
          "slug": "co-developed-leather-patch",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/85ab32c93251f71a2e485ad38e029b6a/69a9a3f79f4956225122393e-pexels-shameel-mukkath-3421394-15059057-1.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "c85ab32c93251f71a2e485ad3",
            "variants": []
          },
          "title": {
            "en": "Co-developed leather patch",
            "vi": "Nhãn da phát triển chung"
          },
          "sortOrder": 3
        },
        {
          "id": "cmqwcchk1lt57ghmuxo",
          "tag": {
            "en": "TPU film",
            "vi": "Phim TPU"
          },
          "desc": {
            "en": "A heat-transferred care and brand label built to your TPU film, wash-test, and placement spec for high-volume runs.",
            "vi": "Nhãn ép nhiệt thông tin và thương hiệu làm theo phim TPU, tiêu chuẩn kiểm tra giặt và vị trí ép cho đơn hàng số lượng lớn."
          },
          "slug": "oem-heat-transfer-label",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/a0c5792c16ff36fde7aad11d2f05a4e4/69a9a296fd1002040c1e9240-pexels-brett-sayles-2126124.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "ca0c5792c16ff36fde7aad11d",
            "variants": []
          },
          "title": {
            "en": "OEM heat-transfer label",
            "vi": "Nhãn ép nhiệt OEM"
          },
          "sortOrder": 4
        },
        {
          "id": "cmqwcchk1y0rj5xhhem",
          "tag": {
            "en": "Etched brass",
            "vi": "Đồng ăn mòn"
          },
          "desc": {
            "en": "An etched brass logo plate manufactured to your CAD file, plating tone, and mounting method as a dedicated OEM component.",
            "vi": "Nhãn logo bằng đồng ăn mòn sản xuất theo file CAD, tông mạ và phương thức gắn của bạn như một linh kiện OEM riêng biệt."
          },
          "slug": "custom-metal-logo-plate",
          "image": {
            "mime": "image/avif",
            "r2Key": "originals/43f0ecc88ceaad99e422630f471df5fd/69a9a01bdb6ad07ce787019a-pexels-slimmars-13-197677686-13801311.avif",
            "width": 2500,
            "height": 1405,
            "assetId": "c43f0ecc88ceaad99e422630f",
            "variants": []
          },
          "title": {
            "en": "Custom metal logo plate",
            "vi": "Nhãn logo kim loại riêng"
          },
          "sortOrder": 5
        }
      ],
      "title": {
        "en": "OEM brand parts",
        "vi": "Linh kiện thương hiệu OEM"
      },
      "sortOrder": 3,
      "productCount": 12,
      "materialCount": 3
    }
  ],
  "catalogSchemaVersion": 1
};
