// AUTO-GENERATED by @signex/api importer (content:import). DO NOT EDIT BY HAND.
// Byte-equal to Release v1's snapshot (canonical JSON). Web build-time fallback for
// getPublishedSnapshot when the DB is empty/unreachable; keeps build + runtime in sync.
import type { ReleaseSnapshot } from "@signex/shared";

export const INITIAL_SNAPSHOT = {
  "assets": {
    "cmqntf8g60001sbis9hmzo3m7": {
      "assetId": "cmqntf8g60001sbis9hmzo3m7",
      "height": 256,
      "mime": "image/svg+xml",
      "r2Key": "originals/7e03ed3b7902e7e5ca8eb130b3018f99/signex-logo.svg",
      "variants": [],
      "width": 613
    },
    "cmqntf8gf000dsbisziho53ky": {
      "assetId": "cmqntf8gf000dsbisziho53ky",
      "height": 630,
      "mime": "image/png",
      "r2Key": "originals/c5bc7b3a9d5caa8a4149a83cc2d0ef08/signex-og.png",
      "variants": [],
      "width": 1200
    },
    "cmqntf8gh000hsbisdlg7qjox": {
      "assetId": "cmqntf8gh000hsbisdlg7qjox",
      "height": 32,
      "mime": "image/png",
      "r2Key": "originals/1e614126d125a4fb8b262ce16f70c3b9/favicon-32x32.png",
      "variants": [],
      "width": 32
    },
    "cmqntf8gj000lsbisyggb66m7": {
      "assetId": "cmqntf8gj000lsbisyggb66m7",
      "height": 16,
      "mime": "image/png",
      "r2Key": "originals/468ff969b95eb24bf5e1dfdbbb554706/favicon-16x16.png",
      "variants": [],
      "width": 16
    },
    "cmqntf8gl000psbisza03hgjf": {
      "assetId": "cmqntf8gl000psbisza03hgjf",
      "height": 180,
      "mime": "image/png",
      "r2Key": "originals/1cad7946bed4ebcd596252a9814fd78b/apple-touch-icon.png",
      "variants": [],
      "width": 180
    },
    "cmqntf8gn000tsbiscedn4l65": {
      "assetId": "cmqntf8gn000tsbiscedn4l65",
      "height": 192,
      "mime": "image/png",
      "r2Key": "originals/117e2896f57a312eaa71ca52c0cdc891/android-chrome-192x192.png",
      "variants": [],
      "width": 192
    },
    "cmqntf8gp000xsbiskb7f6mav": {
      "assetId": "cmqntf8gp000xsbiskb7f6mav",
      "height": 512,
      "mime": "image/png",
      "r2Key": "originals/7f47c710b79aada5a225daf4b41a6141/android-chrome-512x512.png",
      "variants": [],
      "width": 512
    },
    "cmqntf8gs0011sbis22tqievi": {
      "assetId": "cmqntf8gs0011sbis22tqievi",
      "height": 2743,
      "mime": "image/avif",
      "r2Key": "originals/a4b66de045a269b48b297bb6055d43a0/69b04fc10fe79a2becaf38a8-contemporary-cliffside-house-at-twilight.avif",
      "variants": [],
      "width": 4798
    },
    "cmqntf8gw0019sbiske5oznxk": {
      "assetId": "cmqntf8gw0019sbiske5oznxk",
      "height": 2400,
      "mime": "image/avif",
      "r2Key": "originals/a79a1bd46201d96beab5d94daad73cb0/69ac691927961ac98c560fe2-pexels-stephanlouis-19119918.avif",
      "variants": [],
      "width": 1920
    },
    "cmqntf8h1001hsbisu1isocn9": {
      "assetId": "cmqntf8h1001hsbisu1isocn9",
      "height": 720,
      "mime": "image/jpeg",
      "r2Key": "originals/7a51789381425553d5cdf0cea38404ab/69ac9062c7d860e7441b1f36-6168566-hd-1920-1080-30fps-poster-0000000.jpg",
      "variants": [],
      "width": 1280
    },
    "cmqntf8h8001lsbisrmo2a71a": {
      "assetId": "cmqntf8h8001lsbisrmo2a71a",
      "mime": "video/mp4",
      "r2Key": "originals/6cf61765b1292b8c1e4c3a38834731bb/69ac9062c7d860e7441b1f36-6168566-hd-1920-1080-30fps-mp4.mp4",
      "variants": []
    },
    "cmqntf8hh001psbisetb4nruu": {
      "assetId": "cmqntf8hh001psbisetb4nruu",
      "mime": "video/webm",
      "r2Key": "originals/a48c310271c97ca6c8b1cc83b7f54fb6/69ac9062c7d860e7441b1f36-6168566-hd-1920-1080-30fps-webm.webm",
      "variants": []
    },
    "cmqntf8hs0025sbisj0on5n6w": {
      "assetId": "cmqntf8hs0025sbisj0on5n6w",
      "height": 3600,
      "mime": "image/avif",
      "r2Key": "originals/cd18e3b1444659de0a5b6b7479112caf/69b049a16076b1b2188d012d-rumman-amin-s3o2rktkf7i-unsplash.avif",
      "variants": [],
      "width": 2400
    },
    "cmqntf8hu0029sbisbullsdr3": {
      "assetId": "cmqntf8hu0029sbisbullsdr3",
      "height": 1600,
      "mime": "image/avif",
      "r2Key": "originals/47aeed00890ae34ee187193dc6a8f823/69b037b7b9f0bc0f27d8889d-dinuka-lankaloka-hkr5cn6s0q0-unsplash.avif",
      "variants": [],
      "width": 2400
    },
    "cmqntf8hw002dsbisrccnsbxa": {
      "assetId": "cmqntf8hw002dsbisrccnsbxa",
      "height": 1405,
      "mime": "image/avif",
      "r2Key": "originals/68e3e1726da687d5f9c720ee927c27f1/69b03783cb355b95794c522e-pexels-roman-odintsov-5667901.avif",
      "variants": [],
      "width": 2500
    },
    "cmqntf8hx002hsbiskvqeq7tm": {
      "assetId": "cmqntf8hx002hsbiskvqeq7tm",
      "height": 1405,
      "mime": "image/avif",
      "r2Key": "originals/6729c31c0192e90813086218ca51bdce/69aff4da51c27aa9c99aba98-pexels-keeganjchecks-14524361.avif",
      "variants": [],
      "width": 2500
    },
    "cmqntf8hz002lsbisism9guo7": {
      "assetId": "cmqntf8hz002lsbisism9guo7",
      "height": 1405,
      "mime": "image/avif",
      "r2Key": "originals/de4dedb21ef3f3df9b6636351a554c56/69a9a5725487307243a72031-pexels-adriendrj-33980501.avif",
      "variants": [],
      "width": 2500
    },
    "cmqntf8i1002psbis3zk0nmxn": {
      "assetId": "cmqntf8i1002psbis3zk0nmxn",
      "height": 1405,
      "mime": "image/avif",
      "r2Key": "originals/b3c0bc5aa6391c8b09cbf9c8fb3836ae/69a9a51013e52d8aa1532730-pexels-alohaphotostudio-6961666.avif",
      "variants": [],
      "width": 2500
    },
    "cmqntf8i9002tsbisivtbceds": {
      "assetId": "cmqntf8i9002tsbisivtbceds",
      "height": 1405,
      "mime": "image/avif",
      "r2Key": "originals/558390147010589195a164982f35768c/69a9a43eeca7b6045e93b8cd-pexels-freestockpro-1007657.avif",
      "variants": [],
      "width": 2500
    },
    "cmqntf8ib002xsbisrlfs97a6": {
      "assetId": "cmqntf8ib002xsbisrlfs97a6",
      "height": 1405,
      "mime": "image/avif",
      "r2Key": "originals/85ab32c93251f71a2e485ad38e029b6a/69a9a3f79f4956225122393e-pexels-shameel-mukkath-3421394-15059057-1.avif",
      "variants": [],
      "width": 2500
    },
    "cmqntf8id0031sbisr1ajp48m": {
      "assetId": "cmqntf8id0031sbisr1ajp48m",
      "height": 1405,
      "mime": "image/avif",
      "r2Key": "originals/a0c5792c16ff36fde7aad11d2f05a4e4/69a9a296fd1002040c1e9240-pexels-brett-sayles-2126124.avif",
      "variants": [],
      "width": 2500
    },
    "cmqntf8ig0035sbismq8t6vtb": {
      "assetId": "cmqntf8ig0035sbismq8t6vtb",
      "height": 1405,
      "mime": "image/avif",
      "r2Key": "originals/43f0ecc88ceaad99e422630f471df5fd/69a9a01bdb6ad07ce787019a-pexels-slimmars-13-197677686-13801311.avif",
      "variants": [],
      "width": 2500
    }
  },
  "blocks": {
    "about": {
      "body": {
        "en": "Founded in 2003, SIGNEX specializes in manufacturing soft plastic brand identity components made from export-standard materials that are odorless, non-toxic, highly durable, and precisely detailed for the garment, consumer goods, and advertising industries. Since 2016, SIGNEX products have been supplied to international markets, including Europe, Japan, and the United States.",
        "vi": "Với kinh nghiệm sản xuất từ năm 2003, tiền thân SIGNEX là đơn vị tại Việt Nam chuyên sản xuất các sản phẩm nhận diện thương hiệu bằng nhựa dẻo đạt tiêu chuẩn xuất khẩu, không mùi, không độc hại, có độ bền cao và chi tiết sắc nét, phục vụ cho ngành may mặc, và quảng cáo. Từ năm 2016, sản phẩm của SIGNEX đã có mặt tại các thị trường quốc tế như Châu Âu, Nhật Bản và Hoa Kỳ."
      },
      "eyebrow": {
        "en": "Who We Are",
        "vi": "Chúng Tôi Là Ai"
      },
      "mission": {
        "body": {
          "en": "To manufacture reliable brand identity components that help businesses present their brand clearly and consistently across products and markets.",
          "vi": "Sản xuất sản phẩm nhựa dẻo nhận diện thương hiệu giúp doanh nghiệp thể hiện hình ảnh thương hiệu một cách rõ ràng và nhất quán trên sản phẩm và thị trường."
        },
        "items": {
          "en": [
            "Delivering consistent manufacturing quality across every production batch",
            "Supporting brands with reliable OEM manufacturing solutions",
            "Maintaining precise brand standards in every component produced",
            "Building long-term manufacturing partnerships with our clients"
          ],
          "vi": [
            "Đảm bảo chất lượng sản xuất đồng nhất qua từng lô",
            "Cung cấp giải pháp sản xuất OEM đáng tin cậy cho các thương hiệu",
            "Duy trì tiêu chuẩn nhận diện chính xác trong từng sản phẩm",
            "Xây dựng quan hệ hợp tác sản xuất lâu dài với khách hàng"
          ]
        },
        "title": {
          "en": "Our Mission",
          "vi": "Sứ Mệnh"
        }
      },
      "title": {
        "accent": {
          "en": "SIGNEX",
          "vi": "SIGNEX"
        },
        "lead": {
          "en": "About ",
          "vi": "Về "
        }
      },
      "values": {
        "body": {
          "en": "Integrity, ethics, and quality form the foundation for sustainable growth in all of SIGNEX's manufacturing activities.",
          "vi": "Lấy uy tín, đạo đức và chất lượng làm nền tảng phát triển bền vững cho mọi hoạt động sản xuất của SIGNEX."
        },
        "title": {
          "en": "Our Values",
          "vi": "Giá Trị Cốt Lõi"
        }
      },
      "vision": {
        "body": {
          "en": "To become a trusted manufacturing partner for global brands, delivering consistent brand identity components with reliability, precision, and long-term cooperation.",
          "vi": "Trở thành đối tác sản xuất đáng tin cậy của các thương hiệu toàn cầu, cung cấp các chi tiết nhận diện với độ chính xác, tính ổn định và sự hợp tác bền vững."
        },
        "title": {
          "en": "Our Vision",
          "vi": "Tầm Nhìn"
        }
      }
    },
    "aboutPage": {
      "approach": [
        {
          "body": {
            "en": [
              "SIGNEX operates as a direct manufacturer with production managed entirely in-house.",
              "This ensures clear technical communication, full production control, and stable quality across manufacturing batches."
            ],
            "vi": [
              "SIGNEX là nhà sản xuất trực tiếp, toàn bộ quy trình sản xuất được quản lý nội bộ.",
              "Điều này đảm bảo trao đổi kỹ thuật rõ ràng, kiểm soát sản xuất toàn diện và chất lượng ổn định qua từng lô sản xuất."
            ]
          },
          "title": {
            "en": "Direct Manufacturing",
            "vi": "Sản Xuất Trực Tiếp"
          }
        },
        {
          "body": {
            "en": [
              "We understand that brand components are not generic parts.",
              "Our manufacturing approach is therefore aligned with brand requirements, ensuring that each component respects established brand guidelines and maintains a consistent appearance across different production runs."
            ],
            "vi": [
              "Chúng tôi hiểu rằng linh kiện nhận diện thương hiệu không phải là những bộ phận đại trà.",
              "Vì vậy, cách tiếp cận sản xuất của chúng tôi luôn bám sát yêu cầu thương hiệu, đảm bảo mỗi linh kiện tuân thủ đúng quy chuẩn thương hiệu và duy trì sự đồng nhất qua các đợt sản xuất khác nhau."
            ]
          },
          "title": {
            "en": "Brand-Oriented Manufacturing",
            "vi": "Sản Xuất Hướng Thương Hiệu"
          }
        },
        {
          "body": {
            "en": [
              "We believe in building lasting relationships with our clients. Our partnership approach ensures consistent quality, reliable delivery, and continuous improvement.",
              "We maintain transparent communication with our partners to ensure reliability, clarity in technical requirements, and long-term manufacturing stability."
            ],
            "vi": [
              "Chúng tôi tin vào việc xây dựng mối quan hệ lâu dài với khách hàng. Cách hợp tác của chúng tôi đảm bảo chất lượng ổn định, giao hàng đáng tin cậy và cải tiến liên tục.",
              "Chúng tôi duy trì trao đổi minh bạch với đối tác để đảm bảo sự tin cậy, rõ ràng trong yêu cầu kỹ thuật và sự ổn định sản xuất lâu dài."
            ]
          },
          "title": {
            "en": "OEM & Confidentiality",
            "vi": "OEM & Bảo Mật"
          }
        }
      ],
      "capability": {
        "body": {
          "en": "SIGNEX focuses on OEM and custom brand identity manufacturing, with production capabilities designed to meet both technical specifications and brand requirements.",
          "vi": "SIGNEX tập trung vào sản xuất OEM và gia công nhận diện thương hiệu theo yêu cầu, với năng lực sản xuất được thiết kế để đáp ứng cả tiêu chuẩn kỹ thuật lẫn yêu cầu thương hiệu."
        },
        "closing": {
          "en": [
            "We do not pursue mass production at the expense of control.",
            "Our focus is manufacturing accuracy and stability, batch after batch."
          ],
          "vi": [
            "Chúng tôi không chạy theo sản xuất hàng loạt mà đánh đổi khả năng kiểm soát.",
            "Trọng tâm của chúng tôi là độ chính xác và sự ổn định trong sản xuất, qua từng lô."
          ]
        },
        "eyebrow": {
          "en": "Our Expertise",
          "vi": "Chuyên Môn Của Chúng Tôi"
        },
        "groups": [
          {
            "items": {
              "en": [
                "Plastic logos and emblems",
                "Brand labels, badges, and nameplates",
                "Custom identity components for products and packaging",
                "OEM brand parts made to specification"
              ],
              "vi": [
                "Logo và biểu tượng nhựa",
                "Nhãn, phù hiệu và bảng tên thương hiệu",
                "Linh kiện nhận diện tùy chỉnh cho sản phẩm và bao bì",
                "Linh kiện thương hiệu OEM gia công theo yêu cầu"
              ]
            },
            "title": {
              "en": "Core Products",
              "vi": "Sản Phẩm Chính"
            }
          },
          {
            "items": {
              "en": [
                "PVC",
                "TPU",
                "Silicone",
                "Composite plastics",
                "Custom material formulations upon request"
              ],
              "vi": [
                "PVC",
                "TPU",
                "Silicone",
                "Nhựa composite",
                "Công thức vật liệu tùy chỉnh theo yêu cầu"
              ]
            },
            "title": {
              "en": "Materials",
              "vi": "Vật Liệu"
            }
          },
          {
            "items": {
              "en": [
                "Mold-based forming and precision shaping",
                "Consistent surface finishing and color control",
                "Batch stability and repeatability",
                "Adaptability for small to medium production volumes"
              ],
              "vi": [
                "Tạo hình bằng khuôn và định hình chính xác",
                "Hoàn thiện bề mặt đồng nhất và kiểm soát màu sắc",
                "Ổn định và lặp lại giữa các lô",
                "Linh hoạt cho sản lượng nhỏ đến vừa"
              ]
            },
            "title": {
              "en": "Production Strengths",
              "vi": "Thế Mạnh Sản Xuất"
            }
          }
        ],
        "title": {
          "accent": {
            "en": "Capability",
            "vi": "Sản Xuất"
          },
          "lead": {
            "en": "Manufacturing ",
            "vi": "Năng Lực "
          }
        }
      },
      "hero": {
        "subtitle": {
          "en": "Manufacturing Brand Identity Excellence Since Inception",
          "vi": "Xuất sắc trong sản xuất nhận diện thương hiệu từ ngày đầu thành lập"
        },
        "title": {
          "accent": {
            "en": "Signex",
            "vi": "Signex"
          },
          "lead": {
            "en": "About ",
            "vi": "Về "
          }
        }
      },
      "intro": {
        "body": {
          "en": "Excellence in every detail, quality in every product",
          "vi": "Xuất sắc trong từng chi tiết, chất lượng trong từng sản phẩm"
        },
        "eyebrow": {
          "en": "Why SIGNEX",
          "vi": "Vì Sao Chọn SIGNEX"
        },
        "title": {
          "accent": {
            "en": "Signex",
            "vi": "Signex"
          },
          "lead": {
            "en": "Why Choose ",
            "vi": "Vì Sao Chọn "
          }
        }
      },
      "process": {
        "body": {
          "en": "Excellence in every detail, quality in every product",
          "vi": "Xuất sắc trong từng chi tiết, chất lượng trong từng sản phẩm"
        },
        "eyebrow": {
          "en": "Our Process",
          "vi": "Quy Trình"
        },
        "steps": [
          {
            "body": {
              "en": "Materials are selected and prepared according to performance requirements and product specifications.",
              "vi": "Vật liệu được chọn lọc và chuẩn bị theo yêu cầu về hiệu năng và thông số sản phẩm."
            },
            "title": {
              "en": "Material Selection & Formulation",
              "vi": "Chọn Lọc & Pha Chế Vật Liệu"
            }
          },
          {
            "body": {
              "en": "Precision molds are developed to ensure accurate form reproduction and stable long-term production.",
              "vi": "Khuôn chính xác được phát triển để đảm bảo tái tạo hình dạng chuẩn xác và sản xuất ổn định lâu dài."
            },
            "title": {
              "en": "Mold Development & Tooling",
              "vi": "Phát Triển Khuôn & Gia Công"
            }
          },
          {
            "body": {
              "en": "Components are manufactured under controlled parameters to maintain consistent shape, surface quality, and color.",
              "vi": "Linh kiện được sản xuất dưới các thông số kiểm soát để duy trì hình dạng, chất lượng bề mặt và màu sắc đồng nhất."
            },
            "title": {
              "en": "Production & Forming",
              "vi": "Sản Xuất & Định Hình"
            }
          },
          {
            "body": {
              "en": "Each batch undergoes visual and dimensional inspection to ensure it meets defined standards.",
              "vi": "Mỗi lô đều trải qua kiểm tra ngoại quan và kích thước để đảm bảo đạt các tiêu chuẩn đã định."
            },
            "title": {
              "en": "Quality Inspection",
              "vi": "Kiểm Tra Chất Lượng"
            }
          }
        ],
        "title": {
          "accent": {
            "en": "Approach",
            "vi": "Sản Xuất"
          },
          "lead": {
            "en": "Manufacturing ",
            "vi": "Phương Pháp "
          }
        }
      },
      "testimonial": {
        "body": {
          "en": [
            "SIGNEX is a leading manufacturer specializing in brand identity products. We don't just create brands – we manufacture what brands stand for.",
            "With state-of-the-art manufacturing facilities and a dedicated team of experts, we deliver precision-crafted plastic logos, emblems, labels, badges, nameplates, and custom identity components for global brands.",
            "Our commitment to quality, innovation, and customer satisfaction has made us a trusted partner for businesses seeking excellence in brand representation.",
            "From OEM parts to custom solutions, we bring your brand identity to life through superior manufacturing processes and attention to detail."
          ],
          "vi": [
            "SIGNEX là nhà sản xuất hàng đầu chuyên về các sản phẩm nhận diện thương hiệu. Chúng tôi không chỉ tạo ra thương hiệu – chúng tôi tạo ra những giá trị mà thương hiệu đại diện.",
            "Với hệ thống nhà xưởng hiện đại cùng đội ngũ chuyên gia tận tâm, chúng tôi mang đến các sản phẩm logo nhựa, emblem, nhãn mác, phù hiệu, bảng tên và linh kiện nhận diện tùy chỉnh được gia công với độ chính xác cao cho các thương hiệu toàn cầu.",
            "Sự tận tâm với chất lượng, đổi mới và sự hài lòng của khách hàng đã đưa chúng tôi trở thành đối tác đáng tin cậy của các doanh nghiệp hướng đến sự xuất sắc trong nhận diện thương hiệu.",
            "Từ linh kiện OEM đến các giải pháp tùy chỉnh, chúng tôi hiện thực hóa nhận diện thương hiệu của bạn bằng quy trình sản xuất vượt trội và sự tỉ mỉ trong từng chi tiết."
          ]
        },
        "eyebrow": {
          "en": "Signex",
          "vi": "Signex"
        },
        "title": {
          "accent": {
            "en": "Are",
            "vi": "Ai"
          },
          "lead": {
            "en": "Who We ",
            "vi": "Chúng Tôi Là "
          }
        }
      },
      "timeline": {
        "body": {
          "en": "Our manufacturing process follows a structured, repeatable workflow",
          "vi": "Quy trình sản xuất của chúng tôi tuân theo một luồng công việc có cấu trúc và lặp lại được"
        },
        "eyebrow": {
          "en": "Step by Step",
          "vi": "Từng Bước"
        },
        "intro": {
          "en": [
            "SIGNEX operates as a direct manufacturing company, with production activities conducted under controlled conditions to ensure consistency and quality stability.",
            "Our factory setup focuses on precision forming, material handling, and repeatable production, rather than mass output.",
            "We invest in process control, not scale for scale's sake."
          ],
          "vi": [
            "SIGNEX hoạt động như một công ty sản xuất trực tiếp, với các hoạt động sản xuất được thực hiện trong điều kiện kiểm soát để đảm bảo tính nhất quán và sự ổn định về chất lượng.",
            "Hệ thống nhà xưởng của chúng tôi tập trung vào tạo hình chính xác, xử lý vật liệu và sản xuất lặp lại được, thay vì sản lượng hàng loạt.",
            "Chúng tôi đầu tư vào kiểm soát quy trình, không chạy theo quy mô chỉ để có quy mô."
          ]
        },
        "milestones": [
          {
            "body": {
              "en": "Materials are selected based on performance requirements, durability, and brand application, including PVC, TPU, silicone, and composite plastics.",
              "vi": "Vật liệu được lựa chọn dựa trên yêu cầu về hiệu năng, độ bền và ứng dụng thương hiệu, bao gồm PVC, TPU, silicone và nhựa composite."
            },
            "num": "01",
            "title": {
              "en": "Material Selection & Preparation",
              "vi": "Chọn Lọc & Chuẩn Bị Vật Liệu"
            }
          },
          {
            "body": {
              "en": "Molds are developed or refined to ensure:",
              "vi": "Khuôn được phát triển hoặc tinh chỉnh để đảm bảo:"
            },
            "items": {
              "en": [
                "Accurate form reproduction",
                "Stable batch output",
                "Long-term tooling reliability"
              ],
              "vi": [
                "Tái tạo hình dạng chính xác",
                "Sản lượng lô ổn định",
                "Độ bền khuôn lâu dài"
              ]
            },
            "num": "02",
            "title": {
              "en": "Mold Development & Tooling",
              "vi": "Phát Triển Khuôn & Gia Công"
            }
          },
          {
            "body": {
              "en": "Production is conducted with controlled parameters to ensure:",
              "vi": "Sản xuất được thực hiện với các thông số kiểm soát để đảm bảo:"
            },
            "items": {
              "en": [
                "Shape consistency",
                "Surface quality",
                "Color accuracy"
              ],
              "vi": [
                "Hình dạng đồng nhất",
                "Chất lượng bề mặt",
                "Độ chính xác màu sắc"
              ]
            },
            "num": "03",
            "title": {
              "en": "Production & Forming",
              "vi": "Sản Xuất & Định Hình"
            }
          },
          {
            "body": {
              "en": "Quality checks are integrated throughout production:",
              "vi": "Kiểm tra chất lượng được tích hợp xuyên suốt quá trình sản xuất:"
            },
            "items": {
              "en": [
                "Visual inspection",
                "Dimensional verification",
                "Batch comparison"
              ],
              "vi": [
                "Kiểm tra ngoại quan",
                "Xác minh kích thước",
                "So sánh giữa các lô"
              ]
            },
            "note": {
              "en": "Quality is controlled during production, not corrected afterward.",
              "vi": "Chất lượng được kiểm soát trong quá trình sản xuất, không phải khắc phục sau đó."
            },
            "num": "04",
            "title": {
              "en": "Quality Inspection",
              "vi": "Kiểm Tra Chất Lượng"
            }
          },
          {
            "body": {
              "en": "Final products are finished and packaged to protect:",
              "vi": "Sản phẩm cuối được hoàn thiện và đóng gói để bảo vệ:"
            },
            "items": {
              "en": [
                "Physical integrity",
                "Surface quality",
                "Brand appearance"
              ],
              "vi": [
                "Tính toàn vẹn vật lý",
                "Chất lượng bề mặt",
                "Hình ảnh thương hiệu"
              ]
            },
            "num": "05",
            "title": {
              "en": "Finishing & Packaging",
              "vi": "Hoàn Thiện & Đóng Gói"
            }
          }
        ],
        "title": {
          "accent": {
            "en": "Overview",
            "vi": "Sản Xuất"
          },
          "lead": {
            "en": "Manufacturing Process ",
            "vi": "Tổng Quan Quy Trình "
          }
        }
      }
    },
    "businessContact": {
      "brand": {
        "en": "SIGNEX",
        "vi": "SIGNEX"
      },
      "emails": [
        "core@signex.vn",
        "nhuadeo@gmail.com"
      ],
      "legalName": {
        "en": "SIGNEX BRAND IDENTITY PRODUCTS MANUFACTURING CO., LTD",
        "vi": "CÔNG TY TNHH SẢN XUẤT SẢN PHẨM NHẬN DIỆN THƯƠNG HIỆU SIGNEX"
      },
      "phones": [
        {
          "kind": "tel",
          "label": {
            "en": "Tel",
            "vi": "Tel"
          },
          "value": "(+84) 979 700 072"
        },
        {
          "kind": "zalo",
          "label": {
            "en": "Zalo",
            "vi": "Zalo"
          },
          "value": "(+84) 94 9999 326"
        }
      ],
      "sites": [
        {
          "address": {
            "en": "25/88/13 Bui Quang La, An Hoi Tay ward, Ho Chi Minh city, Viet Nam.",
            "vi": "25/88/13 Bùi Quang Là, phường An Hội Tây, TP.HCM, Việt Nam."
          },
          "kind": "office",
          "label": {
            "en": "Office",
            "vi": "Office"
          }
        },
        {
          "address": {
            "en": "85/45 Duong Thi Muoi, Trung My Tay ward, Ho Chi Minh city, Viet Nam.",
            "vi": "85/45 Dương Thị Mười, phường Trung Mỹ Tây, TP.HCM, Việt Nam."
          },
          "kind": "factory",
          "label": {
            "en": "Factory",
            "vi": "Factory"
          },
          "mapEmbedUrl": "https://www.google.com/maps?q=85%2F45%20D%C6%B0%C6%A1ng%20Th%E1%BB%8B%20M%C6%B0%E1%BB%9Di%2C%20Ph%C6%B0%E1%BB%9Dng%20Trung%20M%E1%BB%B9%20T%C3%A2y%2C%20Tp.HCM&output=embed&z=16"
        }
      ],
      "social": [
        {
          "href": "#",
          "kind": "facebook"
        },
        {
          "href": "#",
          "kind": "youtube"
        },
        {
          "href": "#",
          "kind": "zalo"
        }
      ],
      "taxId": "0319401172",
      "taxLabel": {
        "en": "Tax",
        "vi": "Tax"
      }
    },
    "contactPage": {
      "hero": {
        "subtitle": {
          "en": "Let's discuss how we can bring your brand identity to life",
          "vi": "Hãy cùng trao đổi để hiện thực hóa nhận diện thương hiệu của bạn"
        },
        "title": {
          "accent": {
            "en": "Touch",
            "vi": "Với Chúng Tôi"
          },
          "lead": {
            "en": "Get In ",
            "vi": "Liên Hệ "
          }
        }
      },
      "map": {
        "eyebrow": {
          "en": "Map",
          "vi": "Bản đồ"
        },
        "title": {
          "accent": {
            "en": "Signex",
            "vi": "Signex"
          },
          "lead": {
            "en": "Find ",
            "vi": "Vị trí "
          }
        }
      }
    },
    "features": {
      "cards": [
        {
          "desc": {
            "en": "Clean, controlled processes with full accountability.",
            "vi": "Quy trình rõ ràng, kiểm soát chặt chẽ."
          },
          "title": {
            "en": "Transparent Manufacturing Processes",
            "vi": "Quy Trình Sản Xuất Minh Bạch"
          }
        },
        {
          "desc": {
            "en": "Manufacturing partnerships built for the long term.",
            "vi": "Xây dựng quan hệ hợp tác bền vững theo thời gian."
          },
          "title": {
            "en": "Long-Term Cooperation Mindset",
            "vi": "Định Hướng Hợp Tác Lâu Dài"
          }
        },
        {
          "desc": {
            "en": "Strict adherence to brand standards and specifications.",
            "vi": "Tuân thủ nghiêm ngặt tiêu chuẩn thương hiệu."
          },
          "title": {
            "en": "Respect for Brand Integrity",
            "vi": "Tôn Trọng Tính Toàn Vẹn Thương Hiệu"
          }
        }
      ],
      "cta": {
        "href": "#quote-form",
        "label": {
          "en": "Request a Quote",
          "vi": "Yêu Cầu Báo Giá"
        }
      },
      "eyebrow": {
        "en": "Excellence in Manufacturing Since 2003",
        "vi": "Xuất Sắc Trong Sản Xuất Từ Năm 2003"
      },
      "featured": {
        "desc": {
          "en": "Stable, repeatable quality across every production batch.",
          "vi": "Chất lượng đồng nhất qua từng lô sản xuất."
        },
        "title": {
          "en": "Consistent Production Quality",
          "vi": "Chất Lượng Sản Xuất Ổn Định"
        }
      },
      "title": {
        "accent": {
          "en": "Choose Us",
          "vi": "Chọn Chúng Tôi"
        },
        "lead": {
          "en": "Why Brands",
          "vi": "Vì Sao Các Thương Hiệu"
        }
      },
      "video": {
        "media": {
          "mp4AssetId": "cmqntf8h8001lsbisrmo2a71a",
          "posterAssetId": "cmqntf8h1001hsbisu1isocn9",
          "webmAssetId": "cmqntf8hh001psbisetb4nruu"
        },
        "text": {
          "en": "See how we hold tolerances from sample to finished batch.",
          "vi": "Tìm hiểu cách chúng tôi giữ vững dung sai từ mẫu thử đến lô hàng hoàn thiện."
        },
        "title": {
          "en": "Inside Our Workshop",
          "vi": "Bên Trong Xưởng Sản Xuất"
        }
      }
    },
    "footer": {
      "contactHeading": {
        "en": "Contact us",
        "vi": "Liên hệ"
      },
      "links": [
        {
          "href": "/",
          "label": {
            "en": "Home",
            "vi": "Trang chủ"
          }
        },
        {
          "href": "/about",
          "label": {
            "en": "About",
            "vi": "Về chúng tôi"
          }
        },
        {
          "href": "/contact",
          "label": {
            "en": "Contact",
            "vi": "Liên hệ"
          }
        }
      ],
      "payLabel": {
        "en": "Payment options:",
        "vi": "Phương thức thanh toán:"
      },
      "payments": [
        "VISA",
        "JCB",
        "Napas"
      ],
      "quickHeading": {
        "en": "Quick links",
        "vi": "Truy cập nhanh"
      },
      "shipLabel": {
        "en": "We ship with:",
        "vi": "Hình thức giao hàng:"
      },
      "tagline": {
        "en": [
          "We don't create brands.",
          "We manufacture what brands stand for."
        ],
        "vi": [
          "Chúng tôi không tạo ra thương hiệu.",
          "Chúng tôi tạo ra những giá trị mà thương hiệu đại diện."
        ]
      }
    },
    "formConfig": {
      "fail": {
        "en": "Oops! Something went wrong while submitting the form. Please try again.",
        "vi": "Rất tiếc — đã xảy ra lỗi khi gửi biểu mẫu. Vui lòng thử lại."
      },
      "fields": {
        "email": {
          "label": {
            "en": "Email",
            "vi": "Email"
          },
          "placeholder": {
            "en": "your.email@company.com",
            "vi": "your.email@company.com"
          },
          "required": true
        },
        "height": {
          "label": {
            "en": "Height (mm)",
            "vi": "Dài (mm)"
          },
          "placeholder": {
            "en": "e.g., 50",
            "vi": "vd: 50"
          },
          "required": false
        },
        "message": {
          "label": {
            "en": "Message",
            "vi": "Lời Nhắn"
          },
          "placeholder": {
            "en": "Describe your product requirements...",
            "vi": "Mô tả yêu cầu sản phẩm..."
          },
          "required": false
        },
        "name": {
          "label": {
            "en": "Name",
            "vi": "Tên"
          },
          "placeholder": {
            "en": "Your full name",
            "vi": "Họ và tên"
          },
          "required": true
        },
        "phone": {
          "label": {
            "en": "Phone Number",
            "vi": "Số Điện Thoại"
          },
          "placeholder": {
            "en": "+84 xxx xxx xxxx",
            "vi": "+84 xxx xxx xxxx"
          },
          "required": true
        },
        "quantity": {
          "label": {
            "en": "Quantity",
            "vi": "Số Lượng"
          },
          "placeholder": {
            "en": "e.g., 1000 pieces",
            "vi": "vd: 1000 cái"
          },
          "required": false
        },
        "standard": {
          "label": {
            "en": "Standard",
            "vi": "Tiêu Chuẩn"
          },
          "placeholder": {
            "en": "Select standard",
            "vi": "Chọn tiêu chuẩn"
          },
          "required": false
        },
        "thickness": {
          "label": {
            "en": "Thickness (mm)",
            "vi": "Dày (mm)"
          },
          "placeholder": {
            "en": "e.g., 2",
            "vi": "vd: 2"
          },
          "required": false
        },
        "upload": {
          "label": {
            "en": "Upload Sample",
            "vi": "Tải Mẫu Sản Phẩm"
          },
          "required": false
        },
        "width": {
          "label": {
            "en": "Width (mm)",
            "vi": "Rộng (mm)"
          },
          "placeholder": {
            "en": "e.g., 100",
            "vi": "vd: 100"
          },
          "required": false
        }
      },
      "standardOptions": [
        {
          "label": {
            "en": "OEKO-TEX Standard 100",
            "vi": "OEKO-TEX Standard 100"
          },
          "value": "OEKO-TEX Standard 100"
        },
        {
          "label": {
            "en": "ISO 9001",
            "vi": "ISO 9001"
          },
          "value": "ISO 9001"
        },
        {
          "label": {
            "en": "GRS (Recycled)",
            "vi": "GRS (Tái chế)"
          },
          "value": "GRS (Recycled)"
        },
        {
          "label": {
            "en": "GOTS (Organic)",
            "vi": "GOTS (Hữu cơ)"
          },
          "value": "GOTS (Organic)"
        },
        {
          "label": {
            "en": "Other / Custom",
            "vi": "Khác / Tùy chỉnh"
          },
          "value": "Other / Custom"
        }
      ],
      "submit": {
        "en": "Send Message",
        "vi": "Gửi Thông Tin"
      },
      "success": {
        "en": "Thank you — we've received your request and will get back to you within 24 hours.",
        "vi": "Cảm ơn bạn — chúng tôi đã nhận được yêu cầu và sẽ phản hồi trong vòng 24 giờ."
      },
      "uploadHelp": {
        "en": "JPG, PNG, or PDF (max 10MB)",
        "vi": "JPG, PNG, hoặc PDF (tối đa 10MB)"
      }
    },
    "hero": {
      "image": {
        "alt": {
          "en": "Contemporary cliffside house at twilight",
          "vi": "Nhà trên vách đá lúc hoàng hôn"
        },
        "assetId": "cmqntf8gs0011sbis22tqievi"
      },
      "subtitle": {
        "en": "Specialized in manufacturing logos, emblems, labels, badges, and custom identity components for the garment and fashion industry.",
        "vi": "Chuyên sản xuất logo, emblem, nhãn mác, badge và các chi tiết nhận diện theo yêu cầu cho ngành may mặc và thời trang."
      },
      "titleBottom": {
        "en": "Brand Identity",
        "vi": "Nhận Diện Thương Hiệu"
      },
      "titleTop": {
        "en": "Manufacturing",
        "vi": "Sản Xuất Sản Phẩm"
      }
    },
    "meta": {
      "about": {
        "description": {
          "en": "Inside SIGNEX — our manufacturing capability, approach and process for producing consistent, high-quality brand identity products: logos, emblems, labels, badges, nameplates and custom OEM components.",
          "vi": "Bên trong SIGNEX — năng lực, cách tiếp cận và quy trình sản xuất các sản phẩm nhận diện thương hiệu chất lượng, đồng nhất: logo, emblem, nhãn, huy hiệu, bảng tên và linh kiện OEM theo yêu cầu."
        },
        "title": {
          "en": "About Us",
          "vi": "Về Chúng Tôi"
        }
      },
      "contact": {
        "description": {
          "en": "Get in touch with SIGNEX for a quote on brand identity manufacturing — plastic logos, woven labels, badges, nameplates and custom OEM components. Office and factory in Ho Chi Minh City, Vietnam.",
          "vi": "Liên hệ SIGNEX để nhận báo giá sản xuất sản phẩm nhận diện thương hiệu — logo nhựa, nhãn dệt, huy hiệu, bảng tên và linh kiện OEM theo yêu cầu. Văn phòng và nhà máy tại TP.HCM, Việt Nam."
        },
        "title": {
          "en": "Contact",
          "vi": "Liên Hệ"
        }
      },
      "description": {
        "en": "SIGNEX manufactures brand identity products in Vietnam — plastic logos and emblems, woven and printed labels, badges, nameplates and custom OEM components for fashion and lifestyle brands. Consistent quality, batch after batch.",
        "vi": "SIGNEX sản xuất các sản phẩm nhận diện thương hiệu tại Việt Nam — logo và emblem nhựa, nhãn dệt và in, huy hiệu, bảng tên cùng linh kiện OEM theo yêu cầu cho các thương hiệu thời trang và lifestyle. Chất lượng đồng nhất qua từng lô hàng."
      },
      "favicons": [
        {
          "asset": {
            "assetId": "cmqntf8gh000hsbisdlg7qjox"
          },
          "rel": "icon"
        },
        {
          "asset": {
            "assetId": "cmqntf8gj000lsbisyggb66m7"
          },
          "rel": "icon"
        },
        {
          "asset": {
            "assetId": "cmqntf8gl000psbisza03hgjf"
          },
          "rel": "apple-touch-icon"
        },
        {
          "asset": {
            "assetId": "cmqntf8gn000tsbiscedn4l65"
          },
          "rel": "icon"
        },
        {
          "asset": {
            "assetId": "cmqntf8gp000xsbiskb7f6mav"
          },
          "rel": "icon"
        }
      ],
      "ogImage": {
        "alt": {
          "en": "SIGNEX — Manufacturing Brand Identity",
          "vi": "SIGNEX — Sản Xuất Nhận Diện Thương Hiệu"
        },
        "assetId": "cmqntf8gf000dsbisziho53ky"
      },
      "siteName": "SIGNEX",
      "siteUrl": "https://signex.vn",
      "themeColor": "#071522",
      "title": {
        "en": "SIGNEX — Brand Identity Products Manufacturer",
        "vi": "SIGNEX — Sản Xuất Sản Phẩm Nhận Diện Thương Hiệu"
      }
    },
    "nav": {
      "cta": {
        "href": "#quote-form",
        "label": {
          "en": "Quote Now",
          "vi": "Nhận báo giá"
        }
      },
      "links": [
        {
          "href": "/",
          "label": {
            "en": "Home",
            "vi": "Trang chủ"
          }
        },
        {
          "href": "/about",
          "label": {
            "en": "About",
            "vi": "Về chúng tôi"
          }
        },
        {
          "href": "/contact",
          "label": {
            "en": "Contact",
            "vi": "Liên hệ"
          }
        }
      ],
      "logo": {
        "assetId": "cmqntf8g60001sbis9hmzo3m7"
      },
      "skip": {
        "en": "Skip to content",
        "vi": "Bỏ qua đến nội dung"
      }
    },
    "notFound": {
      "body": {
        "en": "The page you're looking for has moved or no longer exists. Let's get you back on track — Signex is ready to bring your brand identity to life.",
        "vi": "Trang bạn tìm kiếm đã được di chuyển hoặc không còn tồn tại. Hãy quay lại — Signex luôn sẵn sàng hiện thực hóa nhận diện thương hiệu của bạn."
      },
      "cta": {
        "href": "/",
        "label": {
          "en": "Back to homepage",
          "vi": "Về trang chủ"
        }
      },
      "eyebrow": {
        "en": "404",
        "vi": "404"
      },
      "image": {
        "alt": {
          "en": "Signex production floor",
          "vi": "Xưởng sản xuất Signex"
        },
        "assetId": "cmqntf8gw0019sbiske5oznxk"
      },
      "title": {
        "accent": {
          "en": "lost the thread",
          "vi": "đi lạc đường"
        },
        "lead": {
          "en": "Looks like you've ",
          "vi": "Có vẻ bạn đã "
        }
      }
    },
    "productsHeader": {
      "body": {
        "en": "Produced with premium-grade PVC, TPU, silicone, and composite materials, ensuring durability, color stability, and accurate brand representation.",
        "vi": "Sản xuất từ PVC, TPU, silicone và vật liệu composite cao cấp, đảm bảo độ bền, màu sắc ổn định và thể hiện chính xác nhận diện thương hiệu."
      },
      "detail": {
        "listTitle": {
          "accent": {
            "en": "collection",
            "vi": "bộ sản phẩm"
          },
          "lead": {
            "en": "Explore the ",
            "vi": "Khám phá "
          }
        }
      },
      "eyebrow": {
        "en": "Our Products",
        "vi": "Sản Phẩm Của Chúng Tôi"
      },
      "product": {
        "back": {
          "en": "Back to ",
          "vi": "Quay lại "
        },
        "categoryLabel": {
          "en": "Category",
          "vi": "Danh mục"
        },
        "cta": {
          "en": "Request a Quote",
          "vi": "Yêu cầu báo giá"
        },
        "ctaHref": "#quote-form",
        "materialLabel": {
          "en": "Material",
          "vi": "Vật liệu"
        },
        "zoomHint": {
          "en": "Click to zoom",
          "vi": "Nhấn để phóng to"
        }
      },
      "statLabels": {
        "materials": {
          "en": "Materials",
          "vi": "Vật liệu"
        },
        "products": {
          "en": "Products",
          "vi": "Sản phẩm"
        }
      },
      "title": {
        "accent": {
          "en": "Manufacture",
          "vi": "Sản Xuất"
        },
        "lead": {
          "en": "What We ",
          "vi": "Những Gì Chúng Tôi "
        }
      }
    }
  },
  "catalog": {
    "categories": [
      {
        "image": {
          "assetId": "cmqntf8hs0025sbisj0on5n6w",
          "height": 3600,
          "mime": "image/avif",
          "r2Key": "originals/cd18e3b1444659de0a5b6b7479112caf/69b049a16076b1b2188d012d-rumman-amin-s3o2rktkf7i-unsplash.avif",
          "variants": [],
          "width": 2400
        },
        "intro": {
          "en": "Molded and printed plastic brand marks engineered to hold crisp logo geometry and stable color through repeated wash and wear. From soft-PVC patches to silicone heat-transfers and 3D domed emblems, each piece is tooled to your brand spec and finished for apparel, footwear, bags, and accessories.",
          "vi": "Logo và biểu tượng nhựa được đúc và in nhằm giữ nét logo sắc sảo cùng màu sắc ổn định qua nhiều lần giặt và sử dụng. Từ nhãn PVC mềm, logo ép nhiệt silicone đến biểu tượng nổi 3D, mỗi chi tiết đều được làm khuôn theo thông số thương hiệu và hoàn thiện cho hàng may mặc, giày dép, túi xách và phụ kiện."
        },
        "items": [
          {
            "desc": {
              "en": "Flexible 2D or 3D soft-PVC patch with sharp molded detail and a sew-on or heat-seal backing for garments and caps.",
              "vi": "Nhãn PVC mềm 2D hoặc 3D với chi tiết đúc sắc nét, mặt sau may hoặc ép nhiệt, dùng cho quần áo và mũ nón."
            },
            "image": {
              "assetId": "cmqntf8hz002lsbisism9guo7",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/de4dedb21ef3f3df9b6636351a554c56/69a9a5725487307243a72031-pexels-adriendrj-33980501.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "soft-pvc-logo-patch",
            "sortOrder": 0,
            "tag": {
              "en": "Soft PVC",
              "vi": "PVC mềm"
            },
            "title": {
              "en": "Soft-PVC logo patch",
              "vi": "Nhãn logo PVC mềm"
            }
          },
          {
            "desc": {
              "en": "Thin, stretchable silicone mark heat-pressed directly onto fabric for a clean, tagless branded finish.",
              "vi": "Logo silicone mỏng, co giãn, ép nhiệt trực tiếp lên vải, cho bề mặt thương hiệu sạch và không cần nhãn may."
            },
            "image": {
              "assetId": "cmqntf8i1002psbis3zk0nmxn",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/b3c0bc5aa6391c8b09cbf9c8fb3836ae/69a9a51013e52d8aa1532730-pexels-alohaphotostudio-6961666.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "silicone-heat-transfer-logo",
            "sortOrder": 1,
            "tag": {
              "en": "Silicone",
              "vi": "Silicone"
            },
            "title": {
              "en": "Silicone heat-transfer logo",
              "vi": "Logo ép nhiệt silicone"
            }
          },
          {
            "desc": {
              "en": "Printed insert sealed under a glossy doming resin for a raised, scratch-resistant emblem on bags and accessories.",
              "vi": "Tem in được phủ lớp keo PU bóng nổi, tạo biểu tượng cộm chống trầy cho túi xách và phụ kiện."
            },
            "image": {
              "assetId": "cmqntf8i9002tsbisivtbceds",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/558390147010589195a164982f35768c/69a9a43eeca7b6045e93b8cd-pexels-freestockpro-1007657.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "3d-domed-resin-emblem",
            "sortOrder": 2,
            "tag": {
              "en": "Domed Resin",
              "vi": "Phủ keo nổi"
            },
            "title": {
              "en": "3D domed resin emblem",
              "vi": "Biểu tượng nổi phủ keo PU"
            }
          },
          {
            "desc": {
              "en": "Multi-layer rubberized PU badge with embossed edges, giving a soft-touch feel and strong color contrast.",
              "vi": "Logo cao su PU nhiều lớp với viền dập nổi, cho cảm giác mềm tay và độ tương phản màu cao."
            },
            "image": {
              "assetId": "cmqntf8ib002xsbisrlfs97a6",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/85ab32c93251f71a2e485ad38e029b6a/69a9a3f79f4956225122393e-pexels-shameel-mukkath-3421394-15059057-1.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "rubberized-pu-badge",
            "sortOrder": 3,
            "tag": {
              "en": "PU Rubber",
              "vi": "Cao su PU"
            },
            "title": {
              "en": "Rubberized PU badge",
              "vi": "Logo cao su PU"
            }
          },
          {
            "desc": {
              "en": "Hard injection-molded TPU logo with precise edges and fixing posts for footwear and structured bags.",
              "vi": "Logo TPU ép phun cứng với cạnh sắc nét và chấu gắn, dùng cho giày dép và túi có cấu trúc."
            },
            "image": {
              "assetId": "cmqntf8id0031sbisr1ajp48m",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/a0c5792c16ff36fde7aad11d2f05a4e4/69a9a296fd1002040c1e9240-pexels-brett-sayles-2126124.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "injection-molded-logo-trim",
            "sortOrder": 4,
            "tag": {
              "en": "Molded TPU",
              "vi": "TPU ép phun"
            },
            "title": {
              "en": "Injection-molded logo trim",
              "vi": "Logo nhựa ép phun"
            }
          },
          {
            "desc": {
              "en": "Tonal embossed PVC label with raised lettering and stitch channels for a subtle, durable brand mark.",
              "vi": "Nhãn PVC dập nổi cùng tông, chữ nổi và rãnh may sẵn, tạo dấu hiệu thương hiệu tinh tế và bền."
            },
            "image": {
              "assetId": "cmqntf8ig0035sbismq8t6vtb",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/43f0ecc88ceaad99e422630f471df5fd/69a9a01bdb6ad07ce787019a-pexels-slimmars-13-197677686-13801311.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "embossed-pvc-label",
            "sortOrder": 5,
            "tag": {
              "en": "Embossed PVC",
              "vi": "PVC dập nổi"
            },
            "title": {
              "en": "Embossed PVC label",
              "vi": "Nhãn PVC dập nổi"
            }
          }
        ],
        "materialCount": 4,
        "productCount": 18,
        "slug": "plastic-logos-emblems",
        "sortOrder": 0,
        "tag": {
          "en": "PVC · Silicone",
          "vi": "PVC · Silicone"
        },
        "title": {
          "en": "Plastic logos & emblems",
          "vi": "Logo & biểu tượng nhựa"
        }
      },
      {
        "image": {
          "assetId": "cmqntf8hu0029sbisbullsdr3",
          "height": 1600,
          "mime": "image/avif",
          "r2Key": "originals/47aeed00890ae34ee187193dc6a8f823/69b037b7b9f0bc0f27d8889d-dinuka-lankaloka-hkr5cn6s0q0-unsplash.avif",
          "variants": [],
          "width": 2400
        },
        "intro": {
          "en": "Woven, printed and heat-pressed identity trims that carry your brand mark, care information and sizing directly on the garment — produced to consistent specification, batch after batch.",
          "vi": "Các loại nhãn dệt, nhãn in và nhãn ép mang logo, thông tin bảo quản và size ngay trên sản phẩm — gia công đúng quy cách, đồng nhất qua từng lô hàng."
        },
        "items": [
          {
            "desc": {
              "en": "High-density damask weave with crisp logo definition and a soft hand-feel for main and neck labels.",
              "vi": "Nhãn dệt damask mật độ cao cho logo sắc nét, mềm tay, dùng làm nhãn chính và nhãn gáy cổ áo."
            },
            "image": {
              "assetId": "cmqntf8hz002lsbisism9guo7",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/de4dedb21ef3f3df9b6636351a554c56/69a9a5725487307243a72031-pexels-adriendrj-33980501.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "woven-damask-brand-label",
            "sortOrder": 0,
            "tag": {
              "en": "Woven Damask",
              "vi": "Dệt damask"
            },
            "title": {
              "en": "Woven Damask Brand Label",
              "vi": "Nhãn dệt damask"
            }
          },
          {
            "desc": {
              "en": "Smooth satin ribbon printed with wash-care symbols, fiber content and country of origin.",
              "vi": "Dải satin mịn in ký hiệu giặt là, thành phần sợi và xuất xứ, dùng làm nhãn bảo quản."
            },
            "image": {
              "assetId": "cmqntf8i1002psbis3zk0nmxn",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/b3c0bc5aa6391c8b09cbf9c8fb3836ae/69a9a51013e52d8aa1532730-pexels-alohaphotostudio-6961666.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "printed-satin-care-label",
            "sortOrder": 1,
            "tag": {
              "en": "Printed Satin",
              "vi": "In satin"
            },
            "title": {
              "en": "Printed Satin Care Label",
              "vi": "Nhãn in satin"
            }
          },
          {
            "desc": {
              "en": "Center-fold or end-fold size and care tabs with clean cut edges, sewn into seams or side panels.",
              "vi": "Nhãn size, nhãn bảo quản gấp giữa hoặc gấp một biên, bo mép gọn, may vào đường ráp hoặc sườn áo."
            },
            "image": {
              "assetId": "cmqntf8i9002tsbisivtbceds",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/558390147010589195a164982f35768c/69a9a43eeca7b6045e93b8cd-pexels-freestockpro-1007657.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "folded-size-care-tab",
            "sortOrder": 2,
            "tag": {
              "en": "Cotton / Polyester",
              "vi": "Cotton / Polyester"
            },
            "title": {
              "en": "Folded Size & Care Tab",
              "vi": "Nhãn size gấp biên"
            }
          },
          {
            "desc": {
              "en": "Tagless heat-transfer labels pressed directly onto the fabric for soft, irritation-free care marking.",
              "vi": "Nhãn ép nhiệt không cấn cổ, ép trực tiếp lên vải cho cảm giác mềm mại, êm da."
            },
            "image": {
              "assetId": "cmqntf8ib002xsbisrlfs97a6",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/85ab32c93251f71a2e485ad38e029b6a/69a9a3f79f4956225122393e-pexels-shameel-mukkath-3421394-15059057-1.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "heat-transfer-label",
            "sortOrder": 3,
            "tag": {
              "en": "Heat-Transfer",
              "vi": "Ép nhiệt"
            },
            "title": {
              "en": "Heat-Transfer Label",
              "vi": "Nhãn ép nhiệt"
            }
          },
          {
            "desc": {
              "en": "Engraved or etched zinc and brass nameplates with electroplated finish for bags and outerwear.",
              "vi": "Bảng tên kim loại kẽm hoặc đồng, khắc hoặc ăn mòn, mạ điện hoàn thiện, gắn trên túi xách và áo khoác."
            },
            "image": {
              "assetId": "cmqntf8id0031sbisr1ajp48m",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/a0c5792c16ff36fde7aad11d2f05a4e4/69a9a296fd1002040c1e9240-pexels-brett-sayles-2126124.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "engraved-metal-nameplate",
            "sortOrder": 4,
            "tag": {
              "en": "Zinc / Brass",
              "vi": "Kẽm / Đồng"
            },
            "title": {
              "en": "Engraved Metal Nameplate",
              "vi": "Bảng tên kim loại"
            }
          },
          {
            "desc": {
              "en": "Dense machine-embroidered badges with merrowed or laser-cut borders and iron-on or sew-on backing.",
              "vi": "Phù hiệu thêu vi tính dày, viền vắt sổ hoặc cắt laser, đế ép keo hoặc may đính."
            },
            "image": {
              "assetId": "cmqntf8ig0035sbismq8t6vtb",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/43f0ecc88ceaad99e422630f471df5fd/69a9a01bdb6ad07ce787019a-pexels-slimmars-13-197677686-13801311.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "embroidered-badge",
            "sortOrder": 5,
            "tag": {
              "en": "Embroidered",
              "vi": "Thêu vi tính"
            },
            "title": {
              "en": "Embroidered Badge",
              "vi": "Phù hiệu thêu"
            }
          }
        ],
        "materialCount": 6,
        "productCount": 24,
        "slug": "labels-badges-nameplates",
        "sortOrder": 1,
        "tag": {
          "en": "Woven · Printed",
          "vi": "Dệt · In"
        },
        "title": {
          "en": "Labels, badges, nameplates",
          "vi": "Nhãn, phù hiệu & bảng tên"
        }
      },
      {
        "image": {
          "assetId": "cmqntf8hw002dsbisrccnsbxa",
          "height": 1405,
          "mime": "image/avif",
          "r2Key": "originals/68e3e1726da687d5f9c720ee927c27f1/69b03783cb355b95794c522e-pexels-roman-odintsov-5667901.avif",
          "variants": [],
          "width": 2500
        },
        "intro": {
          "en": "Bespoke metal and molded trims engineered to your brand specification, from zipper pulls to rivets and snaps. Each component is tooled to order in zinc alloy, brass, TPU, or soft PVC with custom finishes, logos, and engraving for a consistent identity across every garment.",
          "vi": "Phụ liệu kim loại và đúc khuôn đặt riêng theo đúng yêu cầu thương hiệu, từ tay kéo khóa đến đinh tán và nút bấm. Mỗi chi tiết được làm khuôn theo đơn bằng hợp kim kẽm, đồng thau, TPU hoặc PVC mềm với lớp hoàn thiện, logo và khắc tùy chỉnh, giữ nhận diện đồng nhất trên từng sản phẩm."
        },
        "items": [
          {
            "desc": {
              "en": "Die-cast zinc-alloy pulls shaped to your logo with electroplated or matte finishes for jackets, bags, and outerwear.",
              "vi": "Tay kéo đúc hợp kim kẽm tạo hình theo logo, mạ điện hoặc hoàn thiện mờ, dùng cho áo khoác, túi và đồ mặc ngoài."
            },
            "image": {
              "assetId": "cmqntf8hz002lsbisism9guo7",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/de4dedb21ef3f3df9b6636351a554c56/69a9a5725487307243a72031-pexels-adriendrj-33980501.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "branded-zipper-pulls",
            "sortOrder": 0,
            "tag": {
              "en": "Zinc Alloy",
              "vi": "Hợp kim kẽm"
            },
            "title": {
              "en": "Branded zipper pulls",
              "vi": "Tay kéo khóa khắc logo"
            }
          },
          {
            "desc": {
              "en": "Solid brass shank and tack buttons with laser-engraved or embossed brand marks in antique, nickel, or gunmetal plating.",
              "vi": "Nút cài và nút tán bằng đồng thau khắc laser hoặc dập nổi nhãn hiệu, mạ giả cổ, niken hoặc xám súng."
            },
            "image": {
              "assetId": "cmqntf8i1002psbis3zk0nmxn",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/b3c0bc5aa6391c8b09cbf9c8fb3836ae/69a9a51013e52d8aa1532730-pexels-alohaphotostudio-6961666.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "engraved-metal-buttons",
            "sortOrder": 1,
            "tag": {
              "en": "Brass",
              "vi": "Đồng thau"
            },
            "title": {
              "en": "Engraved metal buttons",
              "vi": "Nút kim loại khắc nhãn"
            }
          },
          {
            "desc": {
              "en": "Made-to-spec side-release and slide buckles cast in zinc or molded in acetal, debossed with your mark for straps and webbing.",
              "vi": "Khóa nhả nhanh và khóa trượt làm theo quy cách, đúc kẽm hoặc ép acetal, dập chìm nhãn hiệu cho dây đai và dây dệt."
            },
            "image": {
              "assetId": "cmqntf8i9002tsbisivtbceds",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/558390147010589195a164982f35768c/69a9a43eeca7b6045e93b8cd-pexels-freestockpro-1007657.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "custom-logo-buckles",
            "sortOrder": 2,
            "tag": {
              "en": "Zinc · Acetal",
              "vi": "Kẽm · Acetal"
            },
            "title": {
              "en": "Custom logo buckles",
              "vi": "Khóa cài dập logo"
            }
          },
          {
            "desc": {
              "en": "Double-cap rivets and decorative studs with a stamped logo head, finished in brass, copper, or black nickel for denim and leather goods.",
              "vi": "Đinh tán hai đầu và đinh trang trí dập logo trên đầu, hoàn thiện đồng thau, đồng đỏ hoặc niken đen cho hàng jeans và đồ da."
            },
            "image": {
              "assetId": "cmqntf8ib002xsbisrlfs97a6",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/85ab32c93251f71a2e485ad38e029b6a/69a9a3f79f4956225122393e-pexels-shameel-mukkath-3421394-15059057-1.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "logo-rivets-studs",
            "sortOrder": 3,
            "tag": {
              "en": "Brass Cap",
              "vi": "Đầu đồng thau"
            },
            "title": {
              "en": "Logo rivets & studs",
              "vi": "Đinh tán khắc logo"
            }
          },
          {
            "desc": {
              "en": "Injection-molded spring cord stoppers and aglets in soft PVC or TPU, raised with a 3D logo and matched to brand Pantone colors.",
              "vi": "Chốt chặn dây lò xo và đầu bọc dây ép phun bằng PVC mềm hoặc TPU, logo nổi 3D và pha màu khớp Pantone thương hiệu."
            },
            "image": {
              "assetId": "cmqntf8id0031sbisr1ajp48m",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/a0c5792c16ff36fde7aad11d2f05a4e4/69a9a296fd1002040c1e9240-pexels-brett-sayles-2126124.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "branded-cord-stoppers",
            "sortOrder": 4,
            "tag": {
              "en": "Soft PVC",
              "vi": "PVC mềm"
            },
            "title": {
              "en": "Branded cord stoppers",
              "vi": "Chốt chặn dây logo nổi"
            }
          },
          {
            "desc": {
              "en": "Self-piercing eyelets, grommets, and ring-spring snap fasteners engraved with your logo in nickel, brass, or matte-black plating.",
              "vi": "Khoen xỏ tự đột, ô-dê và nút bấm bốn phần khắc logo, mạ niken, đồng thau hoặc đen mờ."
            },
            "image": {
              "assetId": "cmqntf8ig0035sbismq8t6vtb",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/43f0ecc88ceaad99e422630f471df5fd/69a9a01bdb6ad07ce787019a-pexels-slimmars-13-197677686-13801311.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "logo-eyelets-snaps",
            "sortOrder": 5,
            "tag": {
              "en": "Plated Metal",
              "vi": "Kim loại mạ"
            },
            "title": {
              "en": "Logo eyelets & snaps",
              "vi": "Ô-dê & nút bấm khắc nhãn"
            }
          }
        ],
        "materialCount": 5,
        "productCount": 15,
        "slug": "custom-identity-components",
        "sortOrder": 2,
        "tag": {
          "en": "Bespoke",
          "vi": "Đặt riêng"
        },
        "title": {
          "en": "Custom identity components",
          "vi": "Linh kiện nhận diện tùy chỉnh"
        }
      },
      {
        "image": {
          "assetId": "cmqntf8hx002hsbiskvqeq7tm",
          "height": 1405,
          "mime": "image/avif",
          "r2Key": "originals/6729c31c0192e90813086218ca51bdce/69aff4da51c27aa9c99aba98-pexels-keeganjchecks-14524361.avif",
          "variants": [],
          "width": 2500
        },
        "intro": {
          "en": "OEM brand parts produced to your exact spec sheet — co-developed trim sets, private-label labels, and branded hardware kits matched to your brand standards. We build to drawing, color, and tolerance, then deliver consistently at production scale.",
          "vi": "Linh kiện thương hiệu OEM sản xuất theo đúng spec sheet của bạn — bộ phụ liệu phát triển chung, nhãn private-label và bộ phụ kiện gắn logo theo chuẩn nhận diện thương hiệu. Chúng tôi làm theo bản vẽ, màu sắc và dung sai, đảm bảo đồng nhất ở quy mô sản xuất hàng loạt."
        },
        "items": [
          {
            "desc": {
              "en": "A coordinated set of labels, tags, and hardware co-developed and color-matched to your brand spec sheet for a single garment program.",
              "vi": "Bộ phụ liệu đồng bộ gồm nhãn, tag treo và phụ kiện kim loại được phát triển chung và đồng màu theo spec sheet thương hiệu cho từng chương trình hàng."
            },
            "image": {
              "assetId": "cmqntf8hz002lsbisism9guo7",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/de4dedb21ef3f3df9b6636351a554c56/69a9a5725487307243a72031-pexels-adriendrj-33980501.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "spec-matched-trim-set",
            "sortOrder": 0,
            "tag": {
              "en": "Mixed materials",
              "vi": "Đa vật liệu"
            },
            "title": {
              "en": "Spec-matched trim set",
              "vi": "Bộ phụ liệu theo spec"
            }
          },
          {
            "desc": {
              "en": "A damask-woven main label produced under your own private label, with brand-locked colors, fonts, and folding to your tech pack.",
              "vi": "Nhãn chính dệt damask sản xuất dưới thương hiệu riêng của bạn, khóa màu, font và kiểu gấp theo đúng tech pack."
            },
            "image": {
              "assetId": "cmqntf8i1002psbis3zk0nmxn",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/b3c0bc5aa6391c8b09cbf9c8fb3836ae/69a9a51013e52d8aa1532730-pexels-alohaphotostudio-6961666.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "private-label-woven-label",
            "sortOrder": 1,
            "tag": {
              "en": "Woven damask",
              "vi": "Dệt damask"
            },
            "title": {
              "en": "Private-label woven label",
              "vi": "Nhãn dệt private-label"
            }
          },
          {
            "desc": {
              "en": "A packaged kit of branded zipper pullers, rivets, and snaps die-cast and electroplated to your logo and finish standard.",
              "vi": "Bộ phụ kiện đóng gói gồm đầu khóa kéo, đinh tán và nút bấm gắn logo, đúc và mạ điện theo chuẩn logo và bề mặt của bạn."
            },
            "image": {
              "assetId": "cmqntf8i9002tsbisivtbceds",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/558390147010589195a164982f35768c/69a9a43eeca7b6045e93b8cd-pexels-freestockpro-1007657.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "branded-hardware-kit",
            "sortOrder": 2,
            "tag": {
              "en": "Zinc alloy",
              "vi": "Hợp kim kẽm"
            },
            "title": {
              "en": "Branded hardware kit",
              "vi": "Bộ phụ kiện gắn logo"
            }
          },
          {
            "desc": {
              "en": "A debossed leather patch developed jointly with your design team, with hide grade, edge finish, and stitch spec fixed to drawing.",
              "vi": "Nhãn da dập chìm phát triển cùng đội thiết kế của bạn, cố định loại da, xử lý cạnh và quy cách đường may theo bản vẽ."
            },
            "image": {
              "assetId": "cmqntf8ib002xsbisrlfs97a6",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/85ab32c93251f71a2e485ad38e029b6a/69a9a3f79f4956225122393e-pexels-shameel-mukkath-3421394-15059057-1.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "co-developed-leather-patch",
            "sortOrder": 3,
            "tag": {
              "en": "Genuine leather",
              "vi": "Da thật"
            },
            "title": {
              "en": "Co-developed leather patch",
              "vi": "Nhãn da phát triển chung"
            }
          },
          {
            "desc": {
              "en": "A heat-transferred care and brand label built to your TPU film, wash-test, and placement spec for high-volume runs.",
              "vi": "Nhãn ép nhiệt thông tin và thương hiệu làm theo phim TPU, tiêu chuẩn kiểm tra giặt và vị trí ép cho đơn hàng số lượng lớn."
            },
            "image": {
              "assetId": "cmqntf8id0031sbisr1ajp48m",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/a0c5792c16ff36fde7aad11d2f05a4e4/69a9a296fd1002040c1e9240-pexels-brett-sayles-2126124.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "oem-heat-transfer-label",
            "sortOrder": 4,
            "tag": {
              "en": "TPU film",
              "vi": "Phim TPU"
            },
            "title": {
              "en": "OEM heat-transfer label",
              "vi": "Nhãn ép nhiệt OEM"
            }
          },
          {
            "desc": {
              "en": "An etched brass logo plate manufactured to your CAD file, plating tone, and mounting method as a dedicated OEM component.",
              "vi": "Nhãn logo bằng đồng ăn mòn sản xuất theo file CAD, tông mạ và phương thức gắn của bạn như một linh kiện OEM riêng biệt."
            },
            "image": {
              "assetId": "cmqntf8ig0035sbismq8t6vtb",
              "height": 1405,
              "mime": "image/avif",
              "r2Key": "originals/43f0ecc88ceaad99e422630f471df5fd/69a9a01bdb6ad07ce787019a-pexels-slimmars-13-197677686-13801311.avif",
              "variants": [],
              "width": 2500
            },
            "slug": "custom-metal-logo-plate",
            "sortOrder": 5,
            "tag": {
              "en": "Etched brass",
              "vi": "Đồng ăn mòn"
            },
            "title": {
              "en": "Custom metal logo plate",
              "vi": "Nhãn logo kim loại riêng"
            }
          }
        ],
        "materialCount": 3,
        "productCount": 12,
        "slug": "oem-brand-parts",
        "sortOrder": 3,
        "tag": {
          "en": "OEM Spec",
          "vi": "Chuẩn OEM"
        },
        "title": {
          "en": "OEM brand parts",
          "vi": "Linh kiện thương hiệu OEM"
        }
      }
    ]
  },
  "schemaVersion": 1
} as const satisfies ReleaseSnapshot;
