import { writeFileSync } from 'node:fs';
import type { ReleaseSnapshot } from '@signex/shared';
import { canonicalJson as _canonicalJson } from '../release/canonical-json';

/**
 * Stable JSON serialization (recursive key-sort, arrays preserve order, bigint throws).
 *
 * Re-exported from `../release/canonical-json` — the SAME function the release engine
 * uses for its checksum, so emit + checksum + DB snapshot are all one source of truth.
 * Do NOT redefine it here; byte-equality requires the same code path.
 */
export { canonicalJson } from '../release/canonical-json';

const BANNER = `// AUTO-GENERATED by @signex/api importer (content:import). DO NOT EDIT BY HAND.
// Byte-equal to Release v1's snapshot (canonical JSON). Web build-time fallback for
// getPublishedSnapshot when the DB is empty/unreachable; keeps build + runtime in sync.
import type { ReleaseSnapshot } from "@signex/shared";`;

/**
 * Emit the committed web fallback module at `outPath`.
 *
 * The embedded object is canonical JSON (sorted keys), pretty-printed for review.
 * Round-trip guarantee: canonicalJson(JSON.parse(embedded)) === canonicalJson(snapshot).
 *
 * @param snapshot - A fully-validated ReleaseSnapshot (must pass ReleaseSnapshotSchema.parse).
 * @param outPath  - Absolute path to write, e.g. `apps/web/app/lib/initial-snapshot.ts`.
 * @returns The full text of the emitted TS module (same as what was written to disk).
 */
export function emitInitialSnapshot(
  snapshot: ReleaseSnapshot,
  outPath: string,
): string {
  // Serialize via canonicalJson's internal sort then pretty-print — this gives
  // human-readable output while still being canonical (key-order is deterministic).
  const sorted = JSON.parse(_canonicalJson(snapshot)) as unknown;
  const pretty = JSON.stringify(sorted, null, 2);
  const text = `${BANNER}\n\nexport const INITIAL_SNAPSHOT = ${pretty} as const satisfies ReleaseSnapshot;\n`;
  writeFileSync(outPath, text, 'utf8');
  return text;
}
